export const WS_PUBLIC_ORDERS_CONNECTION_START = 'WS_CONNECTION_START';
export const WS_PUBLIC_ORDERS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_PUBLIC_ORDERS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR';
export const WS_PUBLIC_ORDERS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';
export const WS_GET_PUBLIC_ORDERS_MESSAGE = 'WS_GET_ALL_ORDERS_MESSAGE';

export const WS_PRIVATE_ORDERS_CONNECTION_START = 'WS_CONNECTION_START';
export const WS_PRIVATE_ORDERS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_PRIVATE_ORDERS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR';
export const WS_GET_PRIVATE_ORDERS_MESSAGE = 'WS_GET_USER_ORDERS_MESSAGE';
export const WS_PRIVATE_ORDERS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';

export const publicOrdersWsActions = {
  wsInit: WS_PUBLIC_ORDERS_CONNECTION_START,
  onOpen: WS_PUBLIC_ORDERS_CONNECTION_SUCCESS,
  onClose: WS_PUBLIC_ORDERS_CONNECTION_CLOSED,
  onError: WS_PUBLIC_ORDERS_CONNECTION_ERROR,
  onMessage: WS_GET_PUBLIC_ORDERS_MESSAGE
}

export const privateOrdersWsActions = {
  wsInit: WS_PRIVATE_ORDERS_CONNECTION_START,
  onOpen: WS_PRIVATE_ORDERS_CONNECTION_SUCCESS,
  onClose: WS_PRIVATE_ORDERS_CONNECTION_CLOSED,
  onError: WS_PRIVATE_ORDERS_CONNECTION_ERROR,
  onMessage: WS_GET_PRIVATE_ORDERS_MESSAGE
}